# Generated by Django 5.2.11 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('procurement', 'Procurement')], default='warehouse', help_text='Which ordering system this item belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price per unit in AUD', max_digits=10),
        ),
    ]
