# Generated by Django 5.2.11 on 2026-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of request', null=True),
        ),
    ]
