# Generated by Django 5.2.11 on 2026-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='week_end_date',
            field=models.DateField(help_text='End date of the pay week'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='week_start_date',
            field=models.DateField(help_text='Start date of the pay week'),
        ),
    ]
