# Generated by Django 5.2.11 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='scheduled_end',
            field=models.TimeField(blank=True, help_text='Scheduled end from roster', null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='scheduled_start',
            field=models.TimeField(blank=True, help_text='Scheduled start from roster', null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Actual end time', null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Actual start time', null=True),
        ),
    ]
