# Generated by Django 5.2.11 on 2026-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Individual end time (overrides shift default)', null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Individual start time (overrides shift default)', null=True),
        ),
        migrations.AlterField(
            model_name='weeklyroster',
            name='week_start_date',
            field=models.DateField(help_text='Start date of the roster week'),
        ),
    ]
