# Generated by Django 5.2.11 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_shiftassignment_end_time_shiftassignment_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('afternoon', 'Afternoon'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyroster',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='role_in_shift',
            field=models.CharField(default='general', help_text='e.g. Cashier, Cook, Counter', max_length=60),
        ),
        migrations.AlterField(
            model_name='weeklyroster',
            name='week_start_date',
            field=models.DateField(help_text='Monday of the roster week'),
        ),
    ]
